image: mcr.microsoft.com/dotnet/sdk:8.0

definitions:
  caches:
    dotnetcore: ~/.nuget/packages

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore BlazorWebTemplate.sln
          - dotnet build BlazorWebTemplate.sln --no-restore -c Release
          - dotnet test BlazorWebTemplate.Tests/BlazorWebTemplate.Tests.csproj --no-build -c Release --logger "console;verbosity=normal"

  pull-requests:
    "**":
      - step:
          name: Build and Test (PR)
          caches:
            - dotnetcore
          script:
            - dotnet restore BlazorWebTemplate.sln
            - dotnet build BlazorWebTemplate.sln --no-restore -c Release
            - dotnet test BlazorWebTemplate.Tests/BlazorWebTemplate.Tests.csproj --no-build -c Release --logger "console;verbosity=normal"
